// frontend2/src/ui/overview.tsx
import * as React from 'react';
import {RouteComponentProps} from 'react-router';
import {connect, DispatchProp} from 'react-redux';
import {AppState} from '../core/AppModel';
import {Summary} from '../core/summary';
import {SummaryComp} from './summary';

class PP {
    userId: string;
}

class OverviewImpl extends React.Component<RouteComponentProps<PP> & DispatchProp<any> & OverviewProps> {
    render() {
        return (
            <div>
                    <div id="accounts" className="alpha prefix_2 grid_6">
                        <h1 className="center no-top-margin">Accounts</h1>
                        {this.props.accounts.map(account =>
                            <SummaryComp summary={account}/>
                        )}
                    </div>
                    <div id="budget" className="prefix_2 grid_6 suffix_2 omega">
                        <h1 className="center no-top-margin">Buckets</h1>
                        {this.props.buckets.map(bucket =>
                            <SummaryComp summary={bucket}/>
                        )}
                    </div>
                </div>
        );
    }
}

const mapStateToProps = (state: AppState, _: RouteComponentProps<{}>): OverviewProps => {
    return {
        accounts: state.accountSummaries,
        buckets: state.bucketSummaries
    };
};

class OverviewProps {
    accounts: Summary[];
    buckets: Summary[];
}

export const Overview = connect(mapStateToProps)(OverviewImpl);

// frontend/src/app/users/overview.component.ts
import {Component, OnInit} from "@angular/core";
import {LoginService} from "../login/login.service";
import {AccountService} from "./account/account.service";
import {Account} from "./account/account";
import {Observable} from "rxjs/Observable";
import {BucketService} from "./budget/bucket.service";
import {Bucket} from "./budget/bucket";
import {Summary} from "./summary/summary";

@Component({
    templateUrl: './overview.component.html'
})
export class OverviewComponent implements OnInit {
    accountss: Observable<Summary<Account>[]>;
    budgetItems: Observable<Summary<Bucket>[]>;

    name: String;

    constructor(private loginService: LoginService,
                private accountService: AccountService,
                private budgetService: BucketService) {
    }

    ngOnInit(): void {
        let userId = this.loginService.getUserId();
        this.accountss = this.accountService.getSummaries(userId);
        this.budgetItems = this.budgetService.getSummaries(userId);
        this.name = this.loginService.getName();
    }
}

<!--<div #welcome class="alpha grid_9">-->
    <!--<h1 class="center">Welcome {{name}}</h1>-->
<!--</div>-->
<div #accounts class="alpha prefix_2 grid_6">
    <h1 class="center no-top-margin">Accounts</h1>
    <summary *ngFor="let account of accountss | async"
             [item]="account"></summary>
</div>
<div #budget class="prefix_2 grid_6 suffix_2 omega">
    <h1 class="center no-top-margin">Budget</h1>
    <summary *ngFor="let budgetItem of budgetItems | async"
             [item]="budgetItem"></summary>
</div>
