// frontend/src/app/users/details.component.ts
import {Component} from "@angular/core";
import {Transaction} from "./transaction/transaction";

@Component({
    templateUrl: './details.component.html'
})
export class DetailsComponent {
    transactions: Transaction[] = [
        {
            items: [{
                date: new Date(2017, 4, 20),
                account: 'Other account',
                comment: 'This is supposed to be a cmmnt',
                amount: 356.15
            }]
        },

        {
            items: [{
                date: new Date(2017, 4, 18),
                account: 'Account with very',
                comment: 'This is also a comment',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 17),
                account: 'Account with very',
                comment: '',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 18),
                account: 'Account with very',
                comment: 'This is also a comment',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 17),
                account: 'Account with very',
                comment: '',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 18),
                account: 'Account with very',
                comment: 'This is also a comment',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 17),
                account: 'Account with very',
                comment: '',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 18),
                account: 'Account with very',
                comment: 'This is also a comment',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 17),
                account: 'Account with very',
                comment: '',
                amount: 123456.78
            }]
        },
        {
            items: [
                {
                    date: new Date(2017, 4, 18),
                    account: 'Account with very',
                    comment: 'This is also a comment',
                    amount: 123456.78
                },
                {
                    date: new Date(2017, 4, 17),
                    account: 'Account with very',
                    comment: '',
                    amount: 123456.78
                }
            ]
        },
        {
            items: [{
                date: new Date(2017, 4, 18),
                account: 'Account with very',
                comment: 'This is also a comment',
                amount: 123456.78
            }]
        },
        {
            items: [{
                date: new Date(2017, 4, 17),
                account: 'Account with very',
                comment: '',
                amount: 123456.78
            }]
        }
    ];

}

<div class="alpha grid_18 omega center"><h1 class="no-top-margin">This is my account</h1></div>
<div class="alpha prefix_1 grid_16 suffix_1 omega transactions">
    <transaction *ngFor="let transaction of transactions" [transaction]="transaction"></transaction>
</div>

// frontend2/src/ui/details.tsx
import * as React from 'react';
import {RouteComponentProps} from 'react-router';
import {Transaction} from '../core/transaction';
import {connect, DispatchProp} from 'react-redux';
import {AppState} from '../core/AppModel';
import {TransactionComp} from './transaction';

export class DetailsImpl extends React.Component<RouteComponentProps<{}> & DispatchProp<any> & DetailsProps> {
    render() {
        return (
            <div>
                <div className="alpha grid_17 omega center">
                    <h1 className="no-top-margin">This is my account</h1>
                </div>
                <div className="alpha grid_15 suffix_2 omega transactions">
                    <div className="alpha grid_3">Date</div>
                    <div className="grid_4">Account / Bucket</div>
                    <div className="grid_6">Comment</div>
                    <div className="grid_2 omega">Amount</div>
                </div>
                <div className="alpha grid_15 suffix_2 omega transactions">
                    {this.props.transactions.map(transaction =>
                        <TransactionComp transaction={transaction} />
                    )}
                </div>
            </div>
        );
    }
}

interface DetailsProps {
    transactions: Transaction[];
}

const mapStateToProps = (state: AppState, _: RouteComponentProps<{}>): DetailsProps => ({
    transactions: state.accountDetails
});

export const Details = connect(mapStateToProps)(DetailsImpl);
