// frontend/src/app/users/summary/summary.component.ts
import {Component, Input} from "@angular/core";
import {Summary} from "./summary";

@Component({
    selector: 'summary',
    template: `
<div class="alpha grid_6 omega">
    <div class="name">{{item.name}}</div>
    <div class="currency" [class.negative]="item.balance < 0">
         {{item.balance | number: '1.2-2'}}
    </div>
</div>
`
})
export class SummaryComponent {
    @Input()
    item: Summary<any>
}

// frontend2/src/ui/summary.tsx
import * as React from 'react';
import {Summary} from '../core/summary';

export class SummaryComp extends React.Component<SummaryProps, {}> {
    render() {
        let balance = this.props.summary.balance;
        let name = this.props.summary.name;

        let className = balance < 0 ?
            'currency negative' : 'currency';

        return (
            <div className="alpha grid_6 omega">
                <div className="name">{name}</div>
                <div className={className}>{balance}</div>
            </div>
        );
    }
}
export class SummaryProps {
    summary: Summary;
}
